name: marian_dart
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  ffi: ^2.0.1
  onnxruntime: ^1.4.1
  #transformers: ^0.2.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
